# Generated by Django 3.1.12 on 2024-12-24 01:41

import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoSuelo',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nitrogeno', models.FloatField()),
                ('potasio', models.FloatField()),
                ('fosforo', models.FloatField()),
                ('ph', models.FloatField()),
                ('conductividad', models.FloatField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_suelo', to='dispositivos.dispositivo')),
            ],
        ),
    ]
