# Generated by Django 3.1.12 on 2024-12-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductividad_min', models.FloatField()),
                ('conductividad_max', models.FloatField()),
            ],
        ),
    ]
