# Generated by Django 3.1.12 on 2024-12-18 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivo',
            name='conductividad_min',
        ),
    ]
